config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  get 'galery', to: 'pages#galery', as: :galery

  get 'menus/:id', to: 'menus#show', as: :menu

  get 'dishes/index'

  resources "contacts", only: [:new, :create]


  resources "contactdishes", only: [:new, :create]

  post 'contacts/precreate' , to: 'contacts#precreate'
  get 'contacts/contact' , to: 'contacts#contact'
  post 'contacts/create_small' , to: 'contacts#create_small'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  # belongs_to :menu
  has_many :contact_dishes
  accepts_nested_attributes_for :contact_dishes

  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :phone, presence: true, numericality: { only_integer: true }, length: { minimum: 9, maximum: 14 },  on: :create
  validates :localization, presence: true
  validates :n_pax, presence: true, numericality: { only_integer: true }, on: :create
  validates :n_ch, presence: true, numericality: { only_integer: true }, on: :create
  validates :menu, presence: true

  # validates :menu_id, inclusion: { in: (eval (Menu.all.map(&:id).join ',').split(",").to_s.gsub('"', '')) }
  validates :date, presence: true
   # validate :date_must_be_in_future

  # def date_must_be_in_future
  #   if date < Date.today
  #     errors.add(:date, "Data incorrecta")
  #   end
  # end

end

app/models/contact_dish.rb
class ContactDish < ApplicationRecord
  belongs_to :contact
  belongs_to :dish
  attr_accessor :comment

end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :menu_dishes
  has_many :contacts
end

app/models/menu.rb
class Menu < ApplicationRecord
  # has_many :menu_dishes
  has_many :contacts
end

app/models/menu_dish.rb
class MenuDish < ApplicationRecord
  # belongs_to :menu
  # belongs_to :dish
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end

end

app/controllers/contact_dishes_controller.rb
class ContactDishesController < ApplicationController

  def new
  end

  def create

  end

  def contactdish_params
    params.require(:contact).permit(:contact_id, :dish_id)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @menus = Menu.all
    @dishes = Dish.all
    @contact = Contact.new
    @contact_dish = ContactDish.new
  end

 def precreate
  @dishes = Dish.all
  @name = contact_params[:name]
  @email = contact_params[:email]
  @phone = contact_params[:phone]
  @n_pax = contact_params[:n_pax]
  @n_ch = contact_params[:n_ch]
  @date = contact_params[:date]
  @location = contact_params[:localization]
  @menu_id = contact_params[:menu]
  @employee = contact_params[:employee]
  @furniture = contact_params[:furniture]
  @palament = contact_params[:palament]

  # if contact_params[:menu_id] != ""
  # @menu_dishes = Menu.find(contact_params[:menu_id]).menu_dishes
  # end
  @menus = Menu.all
  @contact = Contact.new(contact_params)
  unless @contact.valid?
    @error_message = @contact.errors.first
  end

  @contact_dish = ContactDish.new
  render :new
end


def create
    @menus = Menu.all
  @contact = Contact.new(contact_dish_params)

  if @contact.save
    params[:contact_dish][:contact_dishes][1..-1].each do |cd|
      @contact_dish = ContactDish.new(dish_id: cd, contact_id: @contact.id)
      @contact_dish.save
    end
    MailerMailer.send_email(@contact).deliver_now
    flash[:notice] = "A sua mensagem foi enviada. Obrigada!"
    redirect_to root_path
  else
    render :new
  end
end

def contact
   @menus = Menu.all
   @dishes = Dish.all
   @contact = Contact.new
   @contact_dish = ContactDish.new

 end

def create_small
  @menus = Menu.all
  @contact = Contact.new(contact_params)
  if @contact.save
    MailerMailer.send_email(@contact).deliver_now
        flash[:notice] = "A sua mensagem foi enviada. Obrigada!"
    redirect_to root_path
  else
    render :contact
  end

end


private

def contact_params
  params.require(:contact).permit(:name, :email, :phone, :n_pax, :n_ch, :date, :localization, :menu, :comment, :employee, :furniture, :palament)
end

def contact_dish_params
  params.require(:contact_dish).permit(:contact_dishes, :name, :email, :phone, :n_pax, :n_ch, :date, :localization, :menu, :comment, :employee, :furniture, :palament)
end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  def index
    @menus = Menu.all
    @dishes_pet = Dish.where(meal_type:"Para Petiscar")
    @dishes_ac = Dish.where(meal_type:"Para Acordar")
    @dishes_aj = Dish.where(meal_type:"Para Almoçar | Jantar")
    @dishes_acomp = Dish.where(meal_type:"Para Acompanhar")
    @dishes_ter = Dish.where(meal_type:"Para Terminar")
    @dishes_bbr = Dish.where(meal_type:"Para Beber")
    @dishes_all = [@dishes_ac, @dishes_pet, @dishes_aj, @dishes_acomp, @dishes_ter, @dishes_bbr]

  end

  def show
  end

end

app/controllers/menu_dishes_controller.rb
class MenuDishesController < ApplicationController

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def show
    @menus = Menu.all
    @menu = Menu.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @menus = Menu.all
  end

  def about
   @menus = Menu.all
 end

 def contact
   @menus = Menu.all
    @dishes = Dish.all
    @contact = Contact.new
    @contact_dish = ContactDish.new
 end

 def galery
   @menus = Menu.all
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/contacts/_form.html.erb
<% if params[:action] == "new" || params[:action] == "precreate" && !@error_message.nil? %>
<div class="form-all">
  <%= form_for @contact, html: { class: "form-horizontal center" }, url: { action: "precreate" } do |c| %>
  <div class="col-xs-12">
      <div class="title"><p>Preencha por favor os seguintes dados:</p></div>
    <div class="form">
      <% if params[:action] == "precreate" && @error_message.nil?%>
      <%= c.text_field :name, placeholder:"Nome/Empresa", readonly:"readonly" %>
      <% else %>
      <%= c.text_field :name, placeholder:"Nome/Empresa" %>
      <% end %>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:name].present? %>
      <span class="form-error"><%= @contact.errors.messages[:name].first %></span>
      <% end %>
      <% end %>
    </div >
    <div class="form">
      <% if params[:action] == "precreate"&& @error_message.nil? %>
      <%= c.text_field :email, placeholder:"Email", readonly:"readonly" %>
      <% else %>
      <%= c.text_field :email, placeholder:"Email"%>
      <% end %>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:email].present? %>
      <span class="form-error"><%= @contact.errors.messages[:email].first %></span>
      <% end %>
      <% end %>
    </div >
    <div class="form">
      <% if params[:action] == "precreate" && @error_message.nil?%>
      <%= c.text_field :phone , placeholder:"Telefone", readonly:"readonly" %>
      <% else %>
      <%= c.text_field :phone , placeholder:"Telefone" %>
      <% end %>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:phone].present? %>
      <span class="form-error"><%= @contact.errors.messages[:phone].first %></span>
      <% end %>
      <% end %>
      <% if params[:action] == "precreate"&& @error_message.nil? %>
      <%= c.text_field :localization, placeholder:"Local", readonly:"readonly"%>
      <% else %>
      <%= c.text_field :localization, placeholder:"Local"%>
      <% end %>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:localization].present? %>
      <span class="form-error"><%= @contact.errors.messages[:localization].first %></span>
      <% end %>
      <% end %>
    </div>
    <div class="form">
      <% if params[:action] == "precreate"&& @error_message.nil? %>
     <%= c.date_field :date, as: :date, readonly:"readonly"%>
    <% else %>
    <%= c.date_field :date, as: :date%>
    <% end %>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:date].present? %>
      <span class="form-error"><%= @contact.errors.messages[:date].first %></span>
      <% end %>
      <% end %>
      <% if params[:action] == "precreate" && @error_message.nil?%>
     <%= c.text_field :n_pax, placeholder:"Adultos", readonly:"readonly"%>
    <% else %>
     <%= c.text_field :n_pax, placeholder:"Adultos"%>
     <% end %>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:n_pax].present? %>
      <span class="form-error"><%= @contact.errors.messages[:n_pax].first %></span>
      <% end %>
      <% end %>
      <% if params[:action] == "precreate" && @error_message.nil? %>
     <%= c.text_field :n_ch, placeholder:"Crianças", readonly:"readonly" %>
     <% else %>
      <%= c.text_field :n_ch, placeholder:"Crianças" %>
      <% end %>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:n_ch].present? %>
      <span class="form-error"><%= @contact.errors.messages[:n_ch].first %></span>
      <% end %>
      <% end %>
   </div>
     <div class="form">
      <% if params[:action] == "precreate" && @error_message.nil? %>
      <%= c.text_field :menu, placeholder:"Tipo evento (Ex. Cocktail, Coffee Break, After Work ...)", readonly:"readonly"%>
      <% else %>
      <%= c.text_field :menu, placeholder:"Tipo evento (Ex. Cocktail, Coffee Break, After Work ...)"%>
      <% end %>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:menu].present? %>
      <span class="form-error"><%= @contact.errors.messages[:menu].first %></span>
      <% end %>
      <% end %>
   </div>

   <div class="form intro">
     <p>Extras:</p>
   </div>
    <ul><div class="form-att">
      <li><div class="attribute">

        <% if params[:action] == "precreate" && @error_message.nil? %>
        <%= c.check_box :employee, disabled:"true" %>
        <% else %>
        <%= c.check_box :employee %>
        <% end %>
        <%= c.label :employee, "Pessoal p/ servir" %>


        <% if params[:action] == "precreate" && @error_message.nil? %>
        <%= c.check_box :furniture, disabled:"true"   %>
        <% else %>
        <%= c.check_box :furniture%>
        <% end %>
        <%= c.label :furniture, "Mobiliário" %>

        <% if params[:action] == "precreate" && @error_message.nil? %>
        <%= c.check_box :palament, disabled:"true"%>
        <% else %>
        <%= c.check_box :palament%>
        <% end %>
        <%= c.label :palament, "Palamenta" %>

      </div></li>
   </div></ul>
   <div class="form-end">
   <!--  <select required="require" name="contact[menu_id]" id="contact_menu_id">
      <option disabled selected value="" >Tipo de Evento</option>
      <option value="27">Cocktail</option>
      <option value="28">Light Lunch</option>
      <option value="29">Coffee Break</option>
      <option value="30">After Work</option>
    </select> -->
    <% if params[:action] == "new" || params[:action] == "precreate" && !@error_message.nil? %>
    <%= c.submit value="Continuar", :class => "continuar", onclick:"ScrollDown(1)" %>
    <% end %>
  </div >
</div>
<% end %>
</div>
<% end %>

app/views/contacts/_form2.html.erb
<%= form_for @contact_dish , url: { action: "create" } do |c| %>
<div class="form-horizontal field" id="details">
           <div class="subtitle"><p> Percorra as listas (<i class="fas fa-arrows-alt"></i>) e seleccione as opções que desejar:</p></div>
             <div class="box">
    <div class="check-groups">

      <div class="check-group">
        <p>Para Acordar:</p>
        <%= c.collection_check_boxes :contact_dishes, @dishes.where(meal_type:"Para Acordar"), :id, :name do |dish| %>
        <div class="collection-check-box">
          <%= dish.check_box checked: false %>
          <%= dish.label %>
        </div>
        <% end %>
      </div>
      <div class="check-group">
        <p>Para Petiscar:</p>
        <%= c.collection_check_boxes :contact_dishes, @dishes.where(meal_type:"Para Petiscar"), :id, :name do |dish| %>
        <div class="collection-check-box">
          <%= dish.check_box checked: false %>
          <%= dish.label %>
        </div>
        <% end %>
      </div>
      <div class="check-group">
        <p>Para Almoçar | Jantar:</p>
        <%= c.collection_check_boxes :contact_dishes, @dishes.where(meal_type:"Para Almoçar | Jantar"), :id, :name do |dish| %>
        <div class="collection-check-box">
          <%= dish.check_box checked: false %>
          <%= dish.label %>
        </div>
        <% end %>
      </div>
      <div class="check-group">
        <p>Para Acompanhar:</p>
        <%= c.collection_check_boxes :contact_dishes, @dishes.where(meal_type:"Para Acompanhar"), :id, :name do |dish| %>
        <div class="collection-check-box">
          <%= dish.check_box checked: false %>
          <%= dish.label %>
        </div>
        <% end %>
      </div>
      <div class="check-group">
        <p>Para Beber:</p>
        <%= c.collection_check_boxes :contact_dishes, @dishes.where(meal_type:"Para Beber"), :id, :name do |dish| %>
        <div class="collection-check-box">
          <%= dish.check_box checked: false %>
          <%= dish.label %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="add-data">
    <%= c.text_field :comment, placeholder:"Dados adicionais (se necessário)" %>
      <%= c.submit value="Enviar", :class => 'enviar'%>
  </div>
  <% unless @name.nil? %>
  <%= c.hidden_field :name, :value => @name %>
  <%= c.hidden_field :email, :value => @email %>
  <%= c.hidden_field :phone, :value => @phone %>
  <%= c.hidden_field :n_pax, :value => @n_pax %>
  <%= c.hidden_field :n_ch, :value => @n_ch %>
  <%= c.hidden_field :date, :value => @date %>
  <%= c.hidden_field :localization, :value => @location %>
  <%= c.hidden_field :menu, :value => @menu_id %>
  <%= c.hidden_field :employee, :value => @employee %>
  <%= c.hidden_field :furniture, :value => @furniture %>
  <%= c.hidden_field :palament, :value => @palament %>

  <% end %>


  <% end %>
</div>

app/views/contacts/_form3.html.erb
<div class="form-all">

  <%= form_for @contact, html: { class: "form-horizontal center" }, url: { action: "create_small" } do |c| %>
  <!--   <div class="title"><p>Preencha por favor os seguintes dados:</p></div> -->
  <div class="col-xs-12">
    <div class="form">
      <%= c.text_field :name, placeholder:"Nome/Empresa"%>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:name].present? %>
      <span class="form-error"><%= @contact.errors.messages[:name].first %></span>
      <% end %>
      <% end %>
    </div >
    <div class="form">
      <%= c.text_field :email, placeholder:"Email" %>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:email].present? %>
      <span class="form-error"><%= @contact.errors.messages[:email].first %></span>
      <% end %>
      <% end %>
    </div >
    <div class="form">
      <%= c.text_field :phone , placeholder:"Telefone" %>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:phone].present? %>
      <span class="form-error"><%= @contact.errors.messages[:phone].first %></span>
      <% end %>
      <% end %>
      <%= c.text_field :localization, placeholder:"Local"  %>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:localization].present? %>
      <span class="form-error"><%= @contact.errors.messages[:localization].first %></span>
      <% end %>
      <% end %>
    </div>
    <div class="form">
     <%= c.date_field :date, as: :date %>
      <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:date].present? %>
      <span class="form-error"><%= @contact.errors.messages[:date].first %></span>
      <% end %>
      <% end %>
     <%= c.text_field :n_pax, placeholder:"Adultos"%>
     <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:n_pax].present? %>
      <span class="form-error"><%= @contact.errors.messages[:n_pax].first %></span>
      <% end %>
      <% end %>
     <%= c.text_field :n_ch, placeholder:"Crianças" %>
     <% unless @contact.errors.first.nil? %>
      <% if @contact.errors.messages[:n_ch].present? %>
      <span class="form-error"><%= @contact.errors.messages[:n_ch].first %></span>
      <% end %>
      <% end %>
   </div>
   <div class="add-data">
    <%= c.text_field :comment, placeholder:"Mensagem" %>
    <%= c.submit value="Enviar", :class => 'enviar'%>
  </div>
</div>
<%= c.hidden_field :menu, :value => "Mensagem enviada através do formulário simples"%>
<% end %>
</div>

app/views/contacts/contact.html.erb
<div class ="contact-view">
<%= render 'shared/banner_small' %>
  <div class="contact-container">
    <div class="contact-form">
      <h1>Contacte-nos</h1>
      <%= render 'form3' %>
      <div class="contact-data">
        <div class="contact-email">
          <p>varadearames@gmail.com </p>
        </div>
        <div class = "contact-web">
          <a href="https://www.facebook.com/Vara-de-Arames-283953025465518/"><i class="fab fa-facebook-f"></i></a>
          <a href="https://www.instagram.com/varadearames"><i class="fab fa-instagram"></i></a>
          <a href="mailto:varadearames@gmail.com"><i class="fas fa-envelope"></i></a>
        </div>
      </div>
    </div>
    <div class="contact-photo">
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class ="new-view">
<%= render 'shared/banner_small' %>

  <div class = "form-container">
    <div class = "form-scroll">
      <%= render 'form' %>
      <% if params[:action] == "precreate" && params[:contact][:menu_id]!= "" && @error_message.nil? %>
      <%= render 'form2' %>
      <% end %>
    </div>
  </div>
</div>
<!--
<script>
  function _(id) {
  return document.getElementById(id);
}
//_("height").innerText = "Chiều dài của trang: " + Number (document.body.scrollHeight - window.innerHeight) + "px";

function ScrollDown(to) {
  var innerHeight = window.innerHeight;
  var scrollStart = innerHeight * to - innerHeight;
  var scrollEnd = innerHeight * to;
  var timeScroll = 250;
  var fps = 20;

  var scrollInterval = setInterval(function() {
    scrollStart += innerHeight / fps;
    scrollTo(0, scrollStart);
  }, timeScroll / fps);

  setTimeout(function() {
    clearInterval(scrollInterval);
  }, timeScroll);
}
</script> -->

app/views/dishes/index.html.erb
<div class ="index-view">
<%= render 'shared/banner_small' %>
<div class="index-content">
  <div id="myModal2" class="modal">
    <!-- <span class="close cursor" onclick="closeModal()">&times;</span> -->
    <div class="modal-content" id="myContent">
      <div class="mySlides" id="slides-index">
        <!-- <div class="index-opacity" style="background-image: url(/assets/brunch.jpg);"></div> -->
        <div class="index-menu-flex">
          <div class="index-menu-photo">
            <%= image_tag("/assets/acordar.JPG", alt: "acordar") %>
          </div>
          <div class="index-menu">
            <div class="index-menu-title">
              <h1><%= @dishes_all.first.first.meal_type %></h1>
            </div>
            <div class="index-menu-dishes-both">
              <div class="index-menu-dishes">
                <% @dishes_all.first[0..10].each do |dish|  %>
                <p><%= dish.name %></p>
                <% end %>
              </div>
              <div class="index-menu-dishes">
                <% unless @dishes_all.first[11..-1] == nil %>
                <% @dishes_all.first[11..-1].each do |dish|  %>
                <p><%= dish.name %></p>
                <% end %>
                <% end %>
              </div>

              <div class="index-menu-dishes-mobile-land">
                <% @dishes_all.first[0..10].each do |dish|  %>
                <p><%= dish.name %></p>
                <% end %>
              </div>
              <div class="index-menu-dishes-mobile-land">
                <% unless @dishes_all.first[11..-1] == nil %>
                <% @dishes_all.first[9..-1].each do |dish|  %>
                <p><%= dish.name %></p>
                <% end %>
                <% end %>
              </div>

              <div class="index-menu-dishes-mobile">
                <% @dishes_all.first.each do |dish|  %>
                <p><%= dish.name %></p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% j=100 %>
      <% @dishes_all[1..-1].each do |i| %>
      <div class="mySlides" id="slides-index" style="display: none">
        <!-- <div class="index-opacity" style="background-image: url(/assets/brunch.jpg);"></div> -->
        <div class="index-menu-flex">
          <div class="index-menu-photo">
            <img src="/assets/<%= j%>.JPG"  class="decoberta">
            <% j=j+1 %>
          </div>
          <div class="index-menu">
            <div class="index-menu-title">
              <h1><%= i.first.meal_type %></h1>
            </div>
            <div class="index-menu-dishes-both">
              <div class="index-menu-dishes">
                <% i[0..10].each do |dish|  %>
                <p><%= dish.name %></p>
                <% end %>
              </div>
              <div class="index-menu-dishes">
                <% unless i[11..-1] == nil %>
                <% i[11..-1].each do |dish|  %>
                <p><%= dish.name %></p>
                <% end %>
                <% end %>
              </div>
               <div class="index-menu-dishes-mobile-land">
                <% i[0..10].each do |dish|  %>
                <p><%= dish.name %></p>
                <% end %>
              </div>
              <div class="index-menu-dishes-mobile-land">
                <% unless i[11..-1] == nil %>
                <% i[9..-1].each do |dish|  %>
                <p><%= dish.name %></p>
                <% end %>
                <% end %>
              </div>
              <div class="index-menu-dishes-mobile">
                <% i.each do |dish|  %>
                <p><%= dish.name %></p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next" onclick="plusSlides(1)">&#10095;</a>
    </div>
  </div>
  <div class="index-contact-us">
    <a href="/contacts/new" class="btn" data-wipe="Consulte-nos">Consulte-nos</a>
  </div>
</div>
</div>

<script>

  var slideIndex = 1;
  showSlides(slideIndex);

  function plusSlides(n) {
    showSlides(slideIndex += n);
  }

  function currentSlide(n) {
    showSlides(slideIndex = n);
  }

  function showSlides(n) {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    if (n > slides.length) {slideIndex = 1}
      if (n < 1) {slideIndex = slides.length}
        for (i = 0; i < slides.length; i++) {
          slides[i].style.display = "none";
        }
        slides[slideIndex-1].style.display = "block";
      }
    </script>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<div class="background-image">
  <div class="home-contact-us">
        <a href="/contacts/new" class="btn" data-wipe="Consulte-nos">Consulte-nos</a>
      </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <a href="/" ><%= image_tag("/assets/LOGO_nu.png", alt: "logo") %></a>
</div>

<div class="menu">
  <div class = "menu-left">
<!--     <ul> -->
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Catering</a>
      <div class="dropdown-content">

          <%= link_to "VA à descoberta", dishes_index_path %>
      </div>
    </li>
      <li class="dropdown"><a href="/galery">Galeria</a></li>
      <li class="dropdown"><a href="/about">Filosofia</a></li>
      <li class="dropdown"><a href="/contacts/contact">Contactos</a></li>
<!--       </ul> -->
  </div>
      <div class = "menu-right">
        <a href="https://www.facebook.com/Vara-de-Arames-283953025465518/"><i class="fab fa-facebook-f"></i></a>
        <a href="https://www.instagram.com/varadearames"><i class="fab fa-instagram"></i></a>
        <a href="mailto:varadearames@gmail.com"><i class="fas fa-envelope"></i></a>
      </div>
</div>

app/views/shared/_banner_small.html.erb
<div class="banner-small">
  <a href="/" ><%= image_tag("/assets/LOGO_nu.png", alt: "logo") %></a>
</div>

<div class="menu-small">
  <div class = "menu-small-left">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Catering</a>
      <div class="dropdown-content">
          <%= link_to "VA à descoberta", dishes_index_path %>
      </div>
    </li>
      <li class="dropdown"><a href="/galery">Galeria</a></li>
      <li class="dropdown"><a href="/about">Filosofia</a></li>
      <li class="dropdown"><a href="/contacts/contact">Contactos</a></li>
  </div>
      <div class = "menu-small-right">
        <a href="https://www.facebook.com/Vara-de-Arames-283953025465518/"><i class="fab fa-facebook-f"></i></a>
        <a href="https://www.instagram.com/varadearames"><i class="fab fa-instagram"></i></a>
        <a href="mailto:varadearames@gmail.com"><i class="fas fa-envelope"></i></a>
      </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>